In [14]:
import pandas as pd
import numpy as np 
from patsy import  dmatrices
import statsmodels.api  as sm

/Users/yimingcai/anaconda/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools


In [9]:
df  = pd.read_excel("Dataset2.xls")

In [12]:
y, X = dmatrices("np.log(Wage) ~ Female + Age + Educ + Parttime",data= df)

In [16]:
mod =sm.OLS(y,X).fit()

In [23]:
x1, x2 = X[:, :2], X[:, 2:]

In [30]:
P = np.linalg.inv(x1.T.dot(x1)).dot(x1.T).dot(x2)

In [31]:
P

array([[ 40.05063291,   2.25949367,   0.19620253],
       [ -0.11041552,  -0.49318932,   0.24944964]])

In [39]:
b_r = np.linalg.inv(x1.T.dot(x1)).dot(x1.T).dot(y)
b_r

array([[ 4.73364434],
       [-0.25064253]])

In [32]:
mod.params

array([ 3.05268522, -0.04110102,  0.03060617,  0.23317822, -0.36544893])

In [17]:
print (mod.summary())

                            OLS Regression Results                            
Dep. Variable:           np.log(Wage)   R-squared:                       0.704
Model:                            OLS   Adj. R-squared:                  0.702
Method:                 Least Squares   F-statistic:                     294.3
Date:                Tue, 17 Apr 2018   Prob (F-statistic):          2.50e-129
Time:                        22:36:21   Log-Likelihood:                -4.1913
No. Observations:                 500   AIC:                             18.38
Df Residuals:                     495   BIC:                             39.46
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      3.0527      0.055     55.168      0.0

In [ ]:
y_r, X_r = dmatrices("", data= df)
mod_r = sm.OLS(y_r, X_r).fit()

In [18]:
y2, X2 = dmatrices("Age~ Female",data= df)

In [20]:
mod2 =sm.OLS(y2,X2).fit()
print (mod2.summary())

                            OLS Regression Results                            
Dep. Variable:                    Age   R-squared:                       0.000
Model:                            OLS   Adj. R-squared:                 -0.002
Method:                 Least Squares   F-statistic:                   0.01205
Date:                Tue, 17 Apr 2018   Prob (F-statistic):              0.913
Time:                        22:39:58   Log-Likelihood:                -1900.3
No. Observations:                 500   AIC:                             3805.
Df Residuals:                     498   BIC:                             3813.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     40.0506      0.610     65.648      0.0

In [36]:
P = np.array([[40.05, 2.26, 0.2],[-0.11, -0.49, 0.25]])
b2 = np.array([0.031, 0.233, -0.365])

In [40]:
P

array([[ 40.05,   2.26,   0.2 ],
       [ -0.11,  -0.49,   0.25]])

In [41]:
b2

array([ 0.031,  0.233, -0.365])

In [37]:
P.dot(b2)

array([ 1.69513, -0.20883])